name: Pre-commit checks

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run metadata extraction script
        run: |
          echo "Running metadata extraction..."
          chmod +x scripts/extract_metadata.sh
          ./scripts/extract_metadata.sh

      - name: Run pre-commit hooks
        run: pre-commit run --all-files
