name: Sync Documentation to Confluence

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y curl pandoc jq

      - name: Load .env Variables
        run: |
          echo "CONFLUENCE_USER=${{ secrets.CONFLUENCE_USER }}" >> .env
          echo "CONFLUENCE_API_KEY=${{ secrets.CONFLUENCE_API_KEY }}" >> .env
          echo "CONFLUENCE_SPACE=${{ secrets.CONFLUENCE_SPACE }}" >> .env
          echo "CONFLUENCE_URL=${{ secrets.CONFLUENCE_URL }}" >> .env
          echo "CONFLUENCE_ORG_ID=${{ secrets.CONFLUENCE_ORG_ID }}" >> .env
          
       - name: Run Sync Script
          run: |
            chmod +x scripts/sync_to_confluence.sh
            ./scripts/sync_to_confluence.sh
